FROM node:20 AS base
RUN corepack enable
COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile
COPY . .
RUN pnpm run build

FROM base
COPY --from=base build/ ./build/
CMD ["pnpm", "run", "start:prod"]

