version: "3"

services:
  subgraph_deployer:
    image: subgraph_deployer
    depends_on:
      - graph-node_bnb
      - graph-node_eth
      - ipfs_bnb
      - ipfs_eth
      - postgres_bnb
      - postgres_eth
    build: ./local-subgraphs/light-bridge

  graph-node_eth:
    image: graphprotocol/graph-node
    depends_on:
      - ipfs_eth
      - postgres_eth
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      postgres_host: postgres_eth
      postgres_user: graph-node
      postgres_pass: let-me-in
      postgres_db: graph-node
      ipfs: "ipfs_eth:5001"
      ethereum: "local:http://anvil_eth:8545"
      GRAPH_LOG: info
  ipfs_eth:
    image: ipfs/kubo:v0.17.0
  postgres_eth:
    image: postgres:14
    command:
      [
        "postgres",
        "-cshared_preload_libraries=pg_stat_statements",
        "-cmax_connections=200",
      ]
    environment:
      POSTGRES_USER: graph-node
      POSTGRES_PASSWORD: let-me-in
      POSTGRES_DB: graph-node
      # FIXME: remove this env. var. which we shouldn't need. Introduced by
      # <https://github.com/graphprotocol/graph-node/pull/3511>, maybe as a
      # workaround for https://github.com/docker/for-mac/issues/6270?
      PGDATA: "/var/lib/postgresql/data"
      POSTGRES_INITDB_ARGS: "-E UTF8 --locale=C"

  graph-node_bnb:
    image: graphprotocol/graph-node
    depends_on:
      - ipfs_bnb
      - postgres_bnb
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      postgres_host: postgres_bnb
      postgres_user: graph-node
      postgres_pass: let-me-in
      postgres_db: graph-node
      ipfs: "ipfs_bnb:5001"
      ethereum: "local:http://anvil_bnb:8545"
      GRAPH_LOG: info
  ipfs_bnb:
    image: ipfs/kubo:v0.17.0
  postgres_bnb:
    image: postgres:14
    command:
      [
        "postgres",
        "-cshared_preload_libraries=pg_stat_statements",
        "-cmax_connections=200",
      ]
    environment:
      POSTGRES_USER: graph-node
      POSTGRES_PASSWORD: let-me-in
      POSTGRES_DB: graph-node
      # FIXME: remove this env. var. which we shouldn't need. Introduced by
      # <https://github.com/graphprotocol/graph-node/pull/3511>, maybe as a
      # workaround for https://github.com/docker/for-mac/issues/6270?
      PGDATA: "/var/lib/postgresql/data"
      POSTGRES_INITDB_ARGS: "-E UTF8 --locale=C"


  anvil_bnb:
    image: ghcr.io/foundry-rs/foundry:latest
    command:
      - "anvil --hardfork berlin --chain-id 31338" # use legacy tx to emulate boba network
    environment:
      - ANVIL_IP_ADDR=0.0.0.0
#    ports:
#      - "8546:8545"
  anvil_eth:
    image: ghcr.io/foundry-rs/foundry:latest
    command:
      - "anvil --hardfork berlin" # use legacy tx to emulate boba network
    environment:
      - ANVIL_IP_ADDR=0.0.0.0
#    ports:
#      - "8545:8545"

  lightbridge:
    depends_on:
      - lightbridge_db
      - kms
      - anvil_eth
      - anvil_bnb
      - subgraph_deployer
    image: bobanetwork/lightbridge:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    command: bash -c "npm test"
    environment:
      LIGHTBRIDGE_MODE: "testnets"
      LIGHTBRIDGE_REJECT_UNAUTHORIZED: "true"
      # KMS setup (incl. defaults)
      LIGHTBRIDGE_ENV: "dev"
      LIGHTBRIDGE_AWS_KMS_ACCESS_KEY: "1"
      LIGHTBRIDGE_AWS_KMS_SECRET_KEY: "2"
      LIGHTBRIDGE_AWS_KMS_KEY_ID: "lb_disburser_pk"
      LIGHTBRIDGE_AWS_KMS_REGION: "us-east-1"
      LIGHTBRIDGE_AWS_KMS_ENDPOINT: "http://kms:8888/"
      # DB
      LIGHTBRIDGE_POSTGRES_PASSWORD: "abcdef"
      LIGHTBRIDGE_POSTGRES_DB_HOST: "lightbridge_db" # always use local instance for tests
  
  lightbridge_db:
    image: postgres
    deploy:
      replicas: 1
    environment:
      POSTGRES_PASSWORD: "abcdef"
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  #in no way should this be running in production
  kms:
    image: bobanetwork/local-kms:latest
    environment:
      PORT: "8888"
      KMS_REGION: "us-east-1"
    volumes:
      - type: bind
        source: ./test/kms-seed.yml
        target: /init/seed.yaml # must be yaml, yml is not recognized
    ports:
      - 8888:8888