version: "3"

services:
  lightbridge:
    depends_on:
      - kms
    image: bobanetwork/lightbridge:latest
    build:
      context: .
      dockerfile: ./Dockerfile.prod
    command: bash -c "node ./build/src/exec/run.js"
    environment:
      LIGHTBRIDGE_REJECT_UNAUTHORIZED: "${LIGHTBRIDGE_REJECT_UNAUTHORIZED:-false}"
      LIGHTBRIDGE_MODE: "${LIGHTBRIDGE_MODE:-testnets}"
      LIGHTBRIDGE_ENV: "${LIGHTBRIDGE_ENV:-dev}"
      # KMS setup (incl. defaults)
      LIGHTBRIDGE_AWS_KMS_ACCESS_KEY: "${LIGHTBRIDGE_AWS_KMS_ACCESS_KEY:-1}"
      LIGHTBRIDGE_AWS_KMS_SECRET_KEY: "${LIGHTBRIDGE_AWS_KMS_SECRET_KEY:-2}"
      LIGHTBRIDGE_AWS_KMS_KEY_ID: "${LIGHTBRIDGE_AWS_KMS_KEY_ID:-lb_disburser_pk}"
      LIGHTBRIDGE_AWS_KMS_REGION: "${LIGHTBRIDGE_AWS_KMS_REGION:-us-east-1}"
      LIGHTBRIDGE_AWS_KMS_ENDPOINT: "${LIGHTBRIDGE_AWS_KMS_ENDPOINT:-http://kms:8888/}"

  #in no way should this be running in production
  kms:
    image: bobanetwork/local-kms:latest
    environment:
      PORT: "8888"
      KMS_REGION: "us-east-1"
    volumes:
      - type: bind
        source: ./test/kms-seed.yml
        target: /init/seed.yaml # must be yaml, yml is not recognized
    ports:
      - 8888:8888