version: "3"

services: 
  lightbridge:
    depends_on:
      - lightbridge_db
    image: bobanetwork/lightbridge:stable
    build:
      context: .
      dockerfile: ./Dockerfile.prod
    command: bash -c "node ./build/src/exec/run.js"
    env_file:
      - .env
  
  lightbridge_db:
    image: postgres
    deploy:
      replicas: 1
    env_file:
      - .env
    ports:
      - "5432:5432"