name: Build & Release Light Bridge

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build_docker:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_ACCESS_TOKEN_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN_SECRET }}
      - name: Get project versions
        run: |
          echo "version=$(cat ./package.json | jq ".version" | tr -d '"\r\n')" >> $GITHUB_OUTPUT
        id: version
      - name: Build version specific docker image
        run: docker build . --file ./Dockerfile.prod --tag bobanetwork/lightbridge:v${{ steps.version.outputs.version }}
      - name: Push version specific docker image
        run: docker push bobanetwork/lightbridge:v${{ steps.version.outputs.version }}
      - name: Build stable docker image
        run: docker build . --file ./Dockerfile.prod --tag bobanetwork/lightbridge:stable
      - name: Push stable docker image
        run: docker push bobanetwork/lightbridge:stable